# fly.toml app configuration file generated for yuga-roadmap on 2024-02-26T18:04:50+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yuga-roadmap'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
