import { YugaItem } from "./database";

export default function get_test_data(): YugaItem[] {
  return [
    {
      id: 1,
      name: "Apes",
      desc: "lala",
      thumbnail: "",
    },
    {
      id: 2,
      name: "Otherside",
      desc: "lala",
      thumbnail: "",
    },
    {
      id: 3,
      name: "Gaming",
      desc: "lala",
      thumbnail: "",
    },
    {
      id: 4,
      name: "Punks & Meebits",
      desc: "lala",
      thumbnail: "",
    },
    {
      id: 5,
      name: "Moonbirds",
      desc: "kakaw",
      thumbnail: "",
    },
    {
      id: 6,
      name: "Art",
      desc: "viva la artsua (sips espresso)",
      thumbnail: "",
    },
    {
      id: 7,
      parent_id: 1,
      name: "Apefest #1 (NYC-Brooklyn)",
      desc: "OMFG THE BEST",
      thumbnail: "",
      media: "",
      date_delivered: 1635638400,
      date_delivered_end: 1635983999,
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 8,
      parent_id: 1,
      name: "Apefest #2 (NYC-Pier17)",
      desc: 'The second Apefest took place @ Pier 17 in New York City between June 20 - 23, 2022 for verified apes and mutants only (and their +1s). Same venue was used every night, with different musical guests each time. Due to main area being on the rooftop, one of the nights apes got rained on. Snoop Dogg & Eminem appeared live to premier their new music video "From the D 2 the LBC" on the last night of the event.',
      thumbnail: "",
      media: "",
      date_delivered: 1655683200,
      date_delivered_end: 1656028799,
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 9,
      parent_id: 2,
      name: "Apes Come Home",
      desc: "Third trip to the Otherside, reveal of the virtual club house + 3D model for each BAYC ape.",
      thumbnail: "",
      media: "",
      link: "https://news.yuga.com/apes-come-home",
      date_delivered: 1709164800,
      date_delivered_end: 0,
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 10,
      parent_id: 4,
      name: "Acquired Punks and Meebits",
      desc: "Larva Labs remains independent and keeps control of Autoglyphs project while IP of Punks and Meebits is transferred to Yuga. Yuga will grant full commercial rights to holders of the nfts.",
      thumbnail: "",
      media: "",
      link: "https://www.larvalabs.com/blog/2022-3-11-18-0/yuga-labs-acquires-cryptopunks-and-meebits",
      date_delivered: 1646956800,
      date_delivered_end: 0,
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 11,
      parent_id: 5,
      name: "Acquired PROOF Collective",
      desc: "This includes Moonbirds, Mythics, Oddities, and Grails, plus the team and cash reserves. Kevin Rose, the founder of Moonbirds, is moved to advisor role.",
      thumbnail: "",
      media: "",
      link: "https://nftnow.com/news/yuga-labs-acquires-proof/",
      date_delivered: 1708214400,
      date_delivered_end: 0,
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 12,
      parent_id: 6,
      name: "Released TwelveFold Ordinals Collection",
      desc: "300-piece generative art collection inscribed onto satoshis.",
      thumbnail: "",
      media: "",
      link: "https://bitcoinmagazine.com/culture/yuga-labs-introduces-first-bitcoin-ordinals-collection",
      date_delivered: 1677542400,
      date_delivered_end: 0,
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 13,
      parent_id: 6,
      name: "Bitcoin Prizes for Solving Ordinal Puzzles",
      desc: "13 weeks, one puzzle per week. 12 of the puzzles paid out 0.12BTC each and the prize for the 13th was a TwelveFold ordinal.",
      thumbnail: "",
      media: "",
      link: "https://nftnow.com/news/yuga-labs-bitcoin-ordinals-twelvefold-cipher-puzzles/",
      date_delivered: 1693872000,
      date_delivered_end: 1702339200,
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 14,
      parent_id: 3,
      name: "Dookey Dash Unclogged",
      desc: "The web2 version of Dookey Dash for the masses. Closed beta began on March 6th, full release later this spring.",
      thumbnail: "",
      media: "",
      link: "https://news.yuga.com/apes-come-home",
      date_delivered: 0,
      date_delivered_end: 0,
      date_promised_original: 1709251200,
      date_promised_latest: 0,
      date_promised_as_string: "Spring 2024",
      },
    {
      id: 15,
      parent_id: 2,
      name: "Trip #1",
      desc: "The first trip to the Otherside where apes followed Curtis around and then performed the first world boss kill.",
      thumbnail: "",
      media: "https://www.youtube.com/watch?v=x81Eudpc444",
      link: "https://www.youtube.com/watch?v=x81Eudpc444",
      date_delivered: 1657929600,
      date_delivered_end: 0,
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 16,
      parent_id: 2,
      name: "Trip #2",
      desc: "The second trip to the Otherside showcased a few different land/plot types. Apes split up into three teams for a game, with members of the blue team winning and securing a the first Otherside wearable (a helmet) as a reward that was airdropped later.",
      thumbnail: "",
      media: "https://www.youtube.com/watch?v=_RmFWo9Htwg",
      link: "https://www.youtube.com/watch?v=_RmFWo9Htwg",
      date_delivered: 1679702400,
      date_delivered_end: 0,
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 17,
      parent_id: 1,
      name: "Apefest #3 (Hong Kong)",
      desc: "The third Apefest was held in Hong Kong between Nov 3 - 5, 2023 for verified apes and mutants only (and their +1s). It showcased Made by Apes (products and companies created by club members), limited quantities of BAPE merchandise collab, and a huge venue at Kai Tak terminal. Magic Eden partnership was also announced here.",
      thumbnail: "",
      media: "",
      date_delivered: 1698969600,
      date_delivered_end: 1699228799,
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 18,
      parent_id: 1,
      name: "10 000 BAYC go on sale, 0.08 eth each",
      desc: "Apes sell out a week later, on May 1.",
      thumbnail: "",
      media: "",
      date_delivered: 1619136000,
      date_delivered_end: 0,
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 19,
      parent_id: 1,
      name: "The Bathroom Wall",
      desc: "Apes draw together one pixel at a time. Penises abound.",
      thumbnail: "",
      media: "",
      date_delivered: 1619827200,
      date_delivered_end: 0, // ??
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 20,
      parent_id: 1,
      name: "BAKC collection (the doggos)",
      desc: "The free-to-claim drop was followed by a $1M donation to animal shelters. A total of 9602 doggos were claimed/minted.",
      thumbnail: "",
      media: "",
      date_delivered: 1623974400, 
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 21,
      parent_id: 1,
      name: "Merch drop #1: Baby's First Swag",
      desc: "520 items, very limited edition. Yuga admitted they understimated demand due to meteoric rise in club's popularity and promised the next drop to have more items.",
      thumbnail: "",
      media: "",
      date_delivered: 1622332800,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 22,
      parent_id: 1,
      name: "'Fuck it, mutants': MAYC collection drops",
      desc: "20 000 mutants - 10 000 for the apes (free claim) and 10 000 sold at 3 eth mint price. 7500 of the free claim serums were level 1, 2492 were level 2, and 8 were mega serums (all randomly assigned).",
      thumbnail: "",
      media: "",
      date_delivered: 1630108800,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 23,
      parent_id: 1,
      name: "BAYC x The Hundreds merch drop",
      desc: "The first merch collab was a 3-hour drop w/ ape exclusives.",
      thumbnail: "",
      media: "",
      date_delivered: 1629504000,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
      //https://thehundreds.com/blogs/content/the-rise-of-the-meta-apes
    },
    {
      id: 24,
      parent_id: 1,
      name: "Treasure Hunt: 10 eth + 3 NFTs as prize",
      desc: "It was solved within 20 hours by @jtobcat, @bbuerhaus, @_LeFevre_, and @cybourgeoisie. They won 10 eth, 1 BAYC #10, 1 BAKC #10, a level 2 mutant serum, and a 'special surprise'. Many other apes won a decentraland wearable as the bonus prize.",
      thumbnail: "",
      media: "",
      date_delivered: 1631491200,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 25,
      parent_id: 1,
      name: "Sotheby's: 101 apes auctioned for $24M ",
      desc: "",
      thumbnail: "",
      media: "",
      date_delivered: 1631145600,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 26,
      parent_id: 1,
      name: "Christie's Auctions off 6 punks, 4 apes, and 4 Meebits for $12.3M ",
      desc: "",
      thumbnail: "",
      media: "",
      date_delivered: 1632700800,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 27,
      parent_id: 1,
      name: "BAYC x Rolling Stone: 2500 zines printed",
      desc: "Proceeds go to artists whose art was featured in the magazine. The zine fetches 3x+ its cost in the aftermarket.",
      thumbnail: "",
      media: "",
      date_delivered: 1636416000,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 28,
      parent_id: 1,
      name: "BAYC x Adidas Merch Drop",
      desc: "On Dec 2, Adidas bought BAYC #8774 and on Dec 17, in a collab with Gmoney and the team behind the PUNKS comic, released Into the Metaverse nft collection. Each token cost 0.2eth and could be exchanged for physical merch later, in 2022.",
      thumbnail: "",
      media: "",
      date_delivered: 1639699200,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 29,
      parent_id: 1,
      name: "Apes v Mutants Mobile Game",
      desc: "A 7-day sweaty mobile experience where those that slept the least won the best prizes, including a one-of-a-kind ape-themed pinball machine and a mutant Honda Civic.",
      thumbnail: "",
      media: "",
      date_delivered: 1642723200,
      date_delivered_end: 1643328000, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 30,
      parent_id: 1,
      name: "Apes Donate to Ukraine; BAYC Team Adds $1M",
      desc: "The community donated $900k, so after the BAYC team's contribution the total was $1.9M. (As a Ukrainian-American making this website, I just want to say - THANK YOU <3)",
      thumbnail: "",
      media: "",
      date_delivered: 1646697600,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 31,
      parent_id: 2,
      name: "Otherdeeds Released (100 000), Apes Claim for Free",
      desc: "Though the claim was free, the initial hours of the claim were besieged by gas prices as high as 3eth. 10 000 deeds contained Kodas, of which 1000 were mega kodas.",
      thumbnail: "",
      media: "",
      date_delivered: 1651276800,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 32,
      parent_id: 1,
      name: "BAYC x Superlastic: vinyl Curtis toy",
      desc: "Apes can buy a vinyl Curtis toy collectible.",
      thumbnail: "",
      media: "",
      date_delivered: 1649894400,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 33,
      parent_id: 1,
      name: "BAYC x Eminem x Snoop Dogg Merch Drop",
      desc: "",
      thumbnail: "",
      media: "",
      date_delivered: 1656028800,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 34,
      parent_id: 1,
      name: "BAYC x McBess Merch Drop",
      desc: "An ape-only drop w/ the artist's surrealist designs.",
      thumbnail: "",
      media: "",
      date_delivered: 1666742400,
      date_delivered_end: 1667347200, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
    {
      id: 35,
      parent_id: 1,
      name: "BAYC Community Council Formed w/ 7 Apes",
      desc: "The 7 apes: Josh Ong, Sera, Laura Rod, 0xEthan, 0xWave, Negi, and Peter Fang.",
      thumbnail: "",
      media: "",
      date_delivered: 1664928000,
      date_delivered_end: 0, 
      date_promised_original: 0,
      date_promised_latest: 0,
    },
  ];
}